[tool.poetry]
name="SkyAlmanac-Py3"
version="1.0.0"
description=""
authors = ["Aendie Bauer"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.1.0"
pyephem = "^3.7.7"
skyfield = "^1.26"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
